// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: LeaderService.proto

package leadercommunication

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LeaderService_JoinFamily_FullMethodName    = "/LeaderService/JoinFamily"
	LeaderService_GetFamilyList_FullMethodName = "/LeaderService/GetFamilyList"
	LeaderService_SendHeartbeat_FullMethodName = "/LeaderService/SendHeartbeat"
)

// LeaderServiceClient is the client API for LeaderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LeaderServiceClient interface {
	JoinFamily(ctx context.Context, in *FamilyJoinRequest, opts ...grpc.CallOption) (*FamilyJoinResponse, error)
	GetFamilyList(ctx context.Context, in *FamilyListRequest, opts ...grpc.CallOption) (*FamilyListResponse, error)
	SendHeartbeat(ctx context.Context, in *HeartBeatRequest, opts ...grpc.CallOption) (*HeartBeatResponse, error)
}

type leaderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLeaderServiceClient(cc grpc.ClientConnInterface) LeaderServiceClient {
	return &leaderServiceClient{cc}
}

func (c *leaderServiceClient) JoinFamily(ctx context.Context, in *FamilyJoinRequest, opts ...grpc.CallOption) (*FamilyJoinResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FamilyJoinResponse)
	err := c.cc.Invoke(ctx, LeaderService_JoinFamily_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaderServiceClient) GetFamilyList(ctx context.Context, in *FamilyListRequest, opts ...grpc.CallOption) (*FamilyListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FamilyListResponse)
	err := c.cc.Invoke(ctx, LeaderService_GetFamilyList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaderServiceClient) SendHeartbeat(ctx context.Context, in *HeartBeatRequest, opts ...grpc.CallOption) (*HeartBeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartBeatResponse)
	err := c.cc.Invoke(ctx, LeaderService_SendHeartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LeaderServiceServer is the server API for LeaderService service.
// All implementations must embed UnimplementedLeaderServiceServer
// for forward compatibility.
type LeaderServiceServer interface {
	JoinFamily(context.Context, *FamilyJoinRequest) (*FamilyJoinResponse, error)
	GetFamilyList(context.Context, *FamilyListRequest) (*FamilyListResponse, error)
	SendHeartbeat(context.Context, *HeartBeatRequest) (*HeartBeatResponse, error)
	mustEmbedUnimplementedLeaderServiceServer()
}

// UnimplementedLeaderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLeaderServiceServer struct{}

func (UnimplementedLeaderServiceServer) JoinFamily(context.Context, *FamilyJoinRequest) (*FamilyJoinResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method JoinFamily not implemented")
}
func (UnimplementedLeaderServiceServer) GetFamilyList(context.Context, *FamilyListRequest) (*FamilyListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFamilyList not implemented")
}
func (UnimplementedLeaderServiceServer) SendHeartbeat(context.Context, *HeartBeatRequest) (*HeartBeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendHeartbeat not implemented")
}
func (UnimplementedLeaderServiceServer) mustEmbedUnimplementedLeaderServiceServer() {}
func (UnimplementedLeaderServiceServer) testEmbeddedByValue()                       {}

// UnsafeLeaderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LeaderServiceServer will
// result in compilation errors.
type UnsafeLeaderServiceServer interface {
	mustEmbedUnimplementedLeaderServiceServer()
}

func RegisterLeaderServiceServer(s grpc.ServiceRegistrar, srv LeaderServiceServer) {
	// If the following call panics, it indicates UnimplementedLeaderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LeaderService_ServiceDesc, srv)
}

func _LeaderService_JoinFamily_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FamilyJoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaderServiceServer).JoinFamily(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeaderService_JoinFamily_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaderServiceServer).JoinFamily(ctx, req.(*FamilyJoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeaderService_GetFamilyList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FamilyListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaderServiceServer).GetFamilyList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeaderService_GetFamilyList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaderServiceServer).GetFamilyList(ctx, req.(*FamilyListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeaderService_SendHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartBeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaderServiceServer).SendHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeaderService_SendHeartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaderServiceServer).SendHeartbeat(ctx, req.(*HeartBeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LeaderService_ServiceDesc is the grpc.ServiceDesc for LeaderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LeaderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "LeaderService",
	HandlerType: (*LeaderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "JoinFamily",
			Handler:    _LeaderService_JoinFamily_Handler,
		},
		{
			MethodName: "GetFamilyList",
			Handler:    _LeaderService_GetFamilyList_Handler,
		},
		{
			MethodName: "SendHeartbeat",
			Handler:    _LeaderService_SendHeartbeat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "LeaderService.proto",
}
