// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: LeaderService.proto

package leadercommunication

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FamilyJoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Port          string                 `protobuf:"bytes,3,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FamilyJoinRequest) Reset() {
	*x = FamilyJoinRequest{}
	mi := &file_LeaderService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FamilyJoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FamilyJoinRequest) ProtoMessage() {}

func (x *FamilyJoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_LeaderService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FamilyJoinRequest.ProtoReflect.Descriptor instead.
func (*FamilyJoinRequest) Descriptor() ([]byte, []int) {
	return file_LeaderService_proto_rawDescGZIP(), []int{0}
}

func (x *FamilyJoinRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *FamilyJoinRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *FamilyJoinRequest) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

type FamilyJoinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FamilyJoinResponse) Reset() {
	*x = FamilyJoinResponse{}
	mi := &file_LeaderService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FamilyJoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FamilyJoinResponse) ProtoMessage() {}

func (x *FamilyJoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_LeaderService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FamilyJoinResponse.ProtoReflect.Descriptor instead.
func (*FamilyJoinResponse) Descriptor() ([]byte, []int) {
	return file_LeaderService_proto_rawDescGZIP(), []int{1}
}

func (x *FamilyJoinResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type FamilyListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FamilyListRequest) Reset() {
	*x = FamilyListRequest{}
	mi := &file_LeaderService_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FamilyListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FamilyListRequest) ProtoMessage() {}

func (x *FamilyListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_LeaderService_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FamilyListRequest.ProtoReflect.Descriptor instead.
func (*FamilyListRequest) Descriptor() ([]byte, []int) {
	return file_LeaderService_proto_rawDescGZIP(), []int{2}
}

type FamilyListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*FamilyMember        `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FamilyListResponse) Reset() {
	*x = FamilyListResponse{}
	mi := &file_LeaderService_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FamilyListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FamilyListResponse) ProtoMessage() {}

func (x *FamilyListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_LeaderService_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FamilyListResponse.ProtoReflect.Descriptor instead.
func (*FamilyListResponse) Descriptor() ([]byte, []int) {
	return file_LeaderService_proto_rawDescGZIP(), []int{3}
}

func (x *FamilyListResponse) GetMembers() []*FamilyMember {
	if x != nil {
		return x.Members
	}
	return nil
}

type FamilyMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      string                 `protobuf:"bytes,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          string                 `protobuf:"bytes,3,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FamilyMember) Reset() {
	*x = FamilyMember{}
	mi := &file_LeaderService_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FamilyMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FamilyMember) ProtoMessage() {}

func (x *FamilyMember) ProtoReflect() protoreflect.Message {
	mi := &file_LeaderService_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FamilyMember.ProtoReflect.Descriptor instead.
func (*FamilyMember) Descriptor() ([]byte, []int) {
	return file_LeaderService_proto_rawDescGZIP(), []int{4}
}

func (x *FamilyMember) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *FamilyMember) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *FamilyMember) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

type HeartBeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      string                 `protobuf:"bytes,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartBeatRequest) Reset() {
	*x = HeartBeatRequest{}
	mi := &file_LeaderService_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartBeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartBeatRequest) ProtoMessage() {}

func (x *HeartBeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_LeaderService_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartBeatRequest.ProtoReflect.Descriptor instead.
func (*HeartBeatRequest) Descriptor() ([]byte, []int) {
	return file_LeaderService_proto_rawDescGZIP(), []int{5}
}

func (x *HeartBeatRequest) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

type HeartBeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ack           bool                   `protobuf:"varint,1,opt,name=ack,proto3" json:"ack,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartBeatResponse) Reset() {
	*x = HeartBeatResponse{}
	mi := &file_LeaderService_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartBeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartBeatResponse) ProtoMessage() {}

func (x *HeartBeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_LeaderService_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartBeatResponse.ProtoReflect.Descriptor instead.
func (*HeartBeatResponse) Descriptor() ([]byte, []int) {
	return file_LeaderService_proto_rawDescGZIP(), []int{6}
}

func (x *HeartBeatResponse) GetAck() bool {
	if x != nil {
		return x.Ack
	}
	return false
}

var File_LeaderService_proto protoreflect.FileDescriptor

const file_LeaderService_proto_rawDesc = "" +
	"\n" +
	"\x13LeaderService.proto\"P\n" +
	"\x11FamilyJoinRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04port\x18\x03 \x01(\tR\x04port\".\n" +
	"\x12FamilyJoinResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x13\n" +
	"\x11FamilyListRequest\"=\n" +
	"\x12FamilyListResponse\x12'\n" +
	"\amembers\x18\x01 \x03(\v2\r.FamilyMemberR\amembers\"O\n" +
	"\fFamilyMember\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\tR\bmemberId\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x03 \x01(\tR\x04port\"/\n" +
	"\x10HeartBeatRequest\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\tR\bmemberId\"%\n" +
	"\x11HeartBeatResponse\x12\x10\n" +
	"\x03ack\x18\x01 \x01(\bR\x03ack2\xb8\x01\n" +
	"\rLeaderService\x125\n" +
	"\n" +
	"JoinFamily\x12\x12.FamilyJoinRequest\x1a\x13.FamilyJoinResponse\x128\n" +
	"\rGetFamilyList\x12\x12.FamilyListRequest\x1a\x13.FamilyListResponse\x126\n" +
	"\rSendHeartbeat\x12\x11.HeartBeatRequest\x1a\x12.HeartBeatResponseBKZIgithub.com/Technically56/HaToKuSe/proto/leaderservice/leadercommunicationb\x06proto3"

var (
	file_LeaderService_proto_rawDescOnce sync.Once
	file_LeaderService_proto_rawDescData []byte
)

func file_LeaderService_proto_rawDescGZIP() []byte {
	file_LeaderService_proto_rawDescOnce.Do(func() {
		file_LeaderService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_LeaderService_proto_rawDesc), len(file_LeaderService_proto_rawDesc)))
	})
	return file_LeaderService_proto_rawDescData
}

var file_LeaderService_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_LeaderService_proto_goTypes = []any{
	(*FamilyJoinRequest)(nil),  // 0: FamilyJoinRequest
	(*FamilyJoinResponse)(nil), // 1: FamilyJoinResponse
	(*FamilyListRequest)(nil),  // 2: FamilyListRequest
	(*FamilyListResponse)(nil), // 3: FamilyListResponse
	(*FamilyMember)(nil),       // 4: FamilyMember
	(*HeartBeatRequest)(nil),   // 5: HeartBeatRequest
	(*HeartBeatResponse)(nil),  // 6: HeartBeatResponse
}
var file_LeaderService_proto_depIdxs = []int32{
	4, // 0: FamilyListResponse.members:type_name -> FamilyMember
	0, // 1: LeaderService.JoinFamily:input_type -> FamilyJoinRequest
	2, // 2: LeaderService.GetFamilyList:input_type -> FamilyListRequest
	5, // 3: LeaderService.SendHeartbeat:input_type -> HeartBeatRequest
	1, // 4: LeaderService.JoinFamily:output_type -> FamilyJoinResponse
	3, // 5: LeaderService.GetFamilyList:output_type -> FamilyListResponse
	6, // 6: LeaderService.SendHeartbeat:output_type -> HeartBeatResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_LeaderService_proto_init() }
func file_LeaderService_proto_init() {
	if File_LeaderService_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_LeaderService_proto_rawDesc), len(file_LeaderService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_LeaderService_proto_goTypes,
		DependencyIndexes: file_LeaderService_proto_depIdxs,
		MessageInfos:      file_LeaderService_proto_msgTypes,
	}.Build()
	File_LeaderService_proto = out.File
	file_LeaderService_proto_goTypes = nil
	file_LeaderService_proto_depIdxs = nil
}
