// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: NodeService.proto

package communication

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type File struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	FileContent   []byte                 `protobuf:"bytes,2,opt,name=file_content,json=fileContent,proto3" json:"file_content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_NodeService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_NodeService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_NodeService_proto_rawDescGZIP(), []int{0}
}

func (x *File) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *File) GetFileContent() []byte {
	if x != nil {
		return x.FileContent
	}
	return nil
}

type FileHash struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	FileHash      string                 `protobuf:"bytes,2,opt,name=file_hash,json=fileHash,proto3" json:"file_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileHash) Reset() {
	*x = FileHash{}
	mi := &file_NodeService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileHash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileHash) ProtoMessage() {}

func (x *FileHash) ProtoReflect() protoreflect.Message {
	mi := &file_NodeService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileHash.ProtoReflect.Descriptor instead.
func (*FileHash) Descriptor() ([]byte, []int) {
	return file_NodeService_proto_rawDescGZIP(), []int{1}
}

func (x *FileHash) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *FileHash) GetFileHash() string {
	if x != nil {
		return x.FileHash
	}
	return ""
}

type FileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileRequest) Reset() {
	*x = FileRequest{}
	mi := &file_NodeService_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileRequest) ProtoMessage() {}

func (x *FileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_NodeService_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileRequest.ProtoReflect.Descriptor instead.
func (*FileRequest) Descriptor() ([]byte, []int) {
	return file_NodeService_proto_rawDescGZIP(), []int{2}
}

func (x *FileRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

type HeartBeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsAlive       bool                   `protobuf:"varint,1,opt,name=isAlive,proto3" json:"isAlive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartBeatResponse) Reset() {
	*x = HeartBeatResponse{}
	mi := &file_NodeService_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartBeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartBeatResponse) ProtoMessage() {}

func (x *HeartBeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_NodeService_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartBeatResponse.ProtoReflect.Descriptor instead.
func (*HeartBeatResponse) Descriptor() ([]byte, []int) {
	return file_NodeService_proto_rawDescGZIP(), []int{3}
}

func (x *HeartBeatResponse) GetIsAlive() bool {
	if x != nil {
		return x.IsAlive
	}
	return false
}

type HeartBeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartBeatRequest) Reset() {
	*x = HeartBeatRequest{}
	mi := &file_NodeService_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartBeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartBeatRequest) ProtoMessage() {}

func (x *HeartBeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_NodeService_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartBeatRequest.ProtoReflect.Descriptor instead.
func (*HeartBeatRequest) Descriptor() ([]byte, []int) {
	return file_NodeService_proto_rawDescGZIP(), []int{4}
}

type HasFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasFile       bool                   `protobuf:"varint,1,opt,name=hasFile,proto3" json:"hasFile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasFileResponse) Reset() {
	*x = HasFileResponse{}
	mi := &file_NodeService_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasFileResponse) ProtoMessage() {}

func (x *HasFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_NodeService_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasFileResponse.ProtoReflect.Descriptor instead.
func (*HasFileResponse) Descriptor() ([]byte, []int) {
	return file_NodeService_proto_rawDescGZIP(), []int{5}
}

func (x *HasFileResponse) GetHasFile() bool {
	if x != nil {
		return x.HasFile
	}
	return false
}

type FileCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileCountRequest) Reset() {
	*x = FileCountRequest{}
	mi := &file_NodeService_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileCountRequest) ProtoMessage() {}

func (x *FileCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_NodeService_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileCountRequest.ProtoReflect.Descriptor instead.
func (*FileCountRequest) Descriptor() ([]byte, []int) {
	return file_NodeService_proto_rawDescGZIP(), []int{6}
}

type FileCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileCount     int64                  `protobuf:"varint,1,opt,name=file_count,json=fileCount,proto3" json:"file_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileCountResponse) Reset() {
	*x = FileCountResponse{}
	mi := &file_NodeService_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileCountResponse) ProtoMessage() {}

func (x *FileCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_NodeService_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileCountResponse.ProtoReflect.Descriptor instead.
func (*FileCountResponse) Descriptor() ([]byte, []int) {
	return file_NodeService_proto_rawDescGZIP(), []int{7}
}

func (x *FileCountResponse) GetFileCount() int64 {
	if x != nil {
		return x.FileCount
	}
	return 0
}

var File_NodeService_proto protoreflect.FileDescriptor

const file_NodeService_proto_rawDesc = "" +
	"\n" +
	"\x11NodeService.proto\"B\n" +
	"\x04File\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12!\n" +
	"\ffile_content\x18\x02 \x01(\fR\vfileContent\"@\n" +
	"\bFileHash\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x1b\n" +
	"\tfile_hash\x18\x02 \x01(\tR\bfileHash\"&\n" +
	"\vFileRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\"-\n" +
	"\x11HeartBeatResponse\x12\x18\n" +
	"\aisAlive\x18\x01 \x01(\bR\aisAlive\"\x12\n" +
	"\x10HeartBeatRequest\"+\n" +
	"\x0fHasFileResponse\x12\x18\n" +
	"\ahasFile\x18\x01 \x01(\bR\ahasFile\"\x12\n" +
	"\x10FileCountRequest\"2\n" +
	"\x11FileCountResponse\x12\x1d\n" +
	"\n" +
	"file_count\x18\x01 \x01(\x03R\tfileCount2\xe2\x01\n" +
	"\vNodeService\x12\x1d\n" +
	"\tStoreFile\x12\x05.File\x1a\t.FileHash\x12\x1e\n" +
	"\aGetFile\x12\f.FileRequest\x1a\x05.File\x122\n" +
	"\tHeartBeat\x12\x11.HeartBeatRequest\x1a\x12.HeartBeatResponse\x12)\n" +
	"\aHasFile\x12\f.FileRequest\x1a\x10.HasFileResponse\x125\n" +
	"\fGetFileCount\x12\x11.FileCountRequest\x1a\x12.FileCountResponseB7Z5github.com/Technically56/HaToKuSe/proto/communicationb\x06proto3"

var (
	file_NodeService_proto_rawDescOnce sync.Once
	file_NodeService_proto_rawDescData []byte
)

func file_NodeService_proto_rawDescGZIP() []byte {
	file_NodeService_proto_rawDescOnce.Do(func() {
		file_NodeService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_NodeService_proto_rawDesc), len(file_NodeService_proto_rawDesc)))
	})
	return file_NodeService_proto_rawDescData
}

var file_NodeService_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_NodeService_proto_goTypes = []any{
	(*File)(nil),              // 0: File
	(*FileHash)(nil),          // 1: FileHash
	(*FileRequest)(nil),       // 2: FileRequest
	(*HeartBeatResponse)(nil), // 3: HeartBeatResponse
	(*HeartBeatRequest)(nil),  // 4: HeartBeatRequest
	(*HasFileResponse)(nil),   // 5: HasFileResponse
	(*FileCountRequest)(nil),  // 6: FileCountRequest
	(*FileCountResponse)(nil), // 7: FileCountResponse
}
var file_NodeService_proto_depIdxs = []int32{
	0, // 0: NodeService.StoreFile:input_type -> File
	2, // 1: NodeService.GetFile:input_type -> FileRequest
	4, // 2: NodeService.HeartBeat:input_type -> HeartBeatRequest
	2, // 3: NodeService.HasFile:input_type -> FileRequest
	6, // 4: NodeService.GetFileCount:input_type -> FileCountRequest
	1, // 5: NodeService.StoreFile:output_type -> FileHash
	0, // 6: NodeService.GetFile:output_type -> File
	3, // 7: NodeService.HeartBeat:output_type -> HeartBeatResponse
	5, // 8: NodeService.HasFile:output_type -> HasFileResponse
	7, // 9: NodeService.GetFileCount:output_type -> FileCountResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_NodeService_proto_init() }
func file_NodeService_proto_init() {
	if File_NodeService_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_NodeService_proto_rawDesc), len(file_NodeService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_NodeService_proto_goTypes,
		DependencyIndexes: file_NodeService_proto_depIdxs,
		MessageInfos:      file_NodeService_proto_msgTypes,
	}.Build()
	File_NodeService_proto = out.File
	file_NodeService_proto_goTypes = nil
	file_NodeService_proto_depIdxs = nil
}
